### ISSUE TITLE
rpgcen bug: name becomes char

### ISSUE THREAD

**Issue by moonsdad** [apexskier/csci467s15#6]
In tims_client.c generated by rpcgen, we use to have name be an alias for char* now since we're using an an array, rpcgen declares a char for the sample argument for get but ommits the arraysize.
```c
	char  tims_get_1_arg;
```
If we leave name as an alias for char* and declare message elements as arrays, there isn't this issue. We may be able to just add the array size manualy, but it should be noted that this needs to happen at:
tims.h:37,38
tims_client.c:17
tims_clnt.c:28
tims_server.c:22

I think tims.h:54 and tims_xdr.c:xdr_name also need to be modified.
Other [people](http://stackoverflow.com/questions/4523497/typedef-fixed-length-array) have wrapped the array type in a structure to get around problems like this. If we do need to modify tims_xdr.c, I think it would be better to just not use the typedef in tims.x

**Comment by moonsdad** [comment]
I've compared the differences between using
The original:
```c
typedef string name<NAME_LEN>;

struct message {
    name to;
    name from;
    int datetime;
    string content<MSG_LEN>;
};

program TIMS_PROG {
    version TIMS_VERS {
        int TIMS_PUT(message) = 1;
        message TIMS_GET(name) = 2;
    } = 1;
} = 246701xx;
```
My initial proposal:
```c
typedef string name<NAME_LEN>;

struct message {
    char to[NAME_LEN];
    char from[NAME_LEN];
    int datetime;
    char content[MSG_LEN];
};

program TIMS_PROG {
    version TIMS_VERS {
        int TIMS_PUT(message) = 1;
        message TIMS_GET(name) = 2;
    } = 1;
} = 246701xx;
```
The new version:
```c
typedef char name[NAME_LEN];

struct message {
    name to;
    name from;
    int datetime;
    char content[MSG_LEN];
};

program TIMS_PROG {
    version TIMS_VERS {
        int TIMS_PUT(message) = 1;
        message TIMS_GET(name) = 2;
    } = 1;
} = 246701xx;
```
And without any typedefs:
```c
struct message {
    char to[NAME_LEN];
    char from[NAME_LEN];
    int datetime;
    char content[MSG_LEN];
};

program TIMS_PROG {
    version TIMS_VERS {
        int TIMS_PUT(message) = 1;
        message TIMS_GET(char*) = 2;
    } = 1;
} = 246701xx;
```
The new version and without typedefs create char parameters. I suggest we use my original suggestion to avoid any potential problems.

**Comment by apexskier** [comment]
I still like the original `typedef name string<NAME_LEN>`, but okay.

**Comment by moonsdad** [comment]
Updated to use:
```c
typedef string name<NAME_LEN>;

struct message {
    char to[NAME_LEN];
    char from[NAME_LEN];
    int datetime;
    char content[MSG_LEN];
};

program TIMS_PROG {
    version TIMS_VERS {
        int TIMS_PUT(message) = 1;
        message TIMS_GET(name) = 2;
    } = 1;
} = 246701xx;
```
